/**
 * Shelly Script templates.
 *
 * Shelly Script runs on the device (Gen2+) and speaks the Shelly mJS
 * dialect — ES5.1 + a small subset of ES6, plus the `Shelly` runtime
 * API. No arrow functions, no template literals, no let/const in older
 * firmwares — we use var + string concatenation for safety.
 *
 * Each template here is a function that returns final mJS code given
 * parameters. Keep them tight: the cheaper the script, the longer your
 * device lives (scripts have a memory budget of ~24KB code + heap).
 */

/**
 * Power-threshold webhook.
 *
 * Watches the apower field of a switch component (Shelly EM / Plus 1PM /
 * Plus 2PM / etc.) and POSTs to a webhook URL when it crosses a
 * threshold. Includes a cooldown so the user doesn't get spammed.
 *
 * Use case: "Notify me when the laundry machine is running" (threshold
 * 800W), "Alert me on electric shower" (threshold 3000W), etc.
 */
export function powerThresholdWebhook(params: {
  /** Which switch component to watch, defaults to 0 */
  switchIndex?: number
  /** Threshold in watts. Event fires when apower crosses above. */
  thresholdW: number
  /** Full webhook URL on Home Assistant side, e.g. http://192.168.1.10:8123/api/webhook/abc123 */
  webhookUrl: string
  /** Cooldown between events in ms (default 60000) */
  cooldownMs?: number
  /** Optional label included in the payload for disambiguation */
  label?: string
}): string {
  const idx = params.switchIndex ?? 0
  const cooldown = params.cooldownMs ?? 60_000
  const label = (params.label ?? '').replace(/"/g, '\\"')
  const url = params.webhookUrl
  const threshold = params.thresholdW
  return `
// Auto-generated by HA Dispatch. Do not edit on device — re-deploy instead.
var THRESHOLD_W = ${threshold};
var COOLDOWN_MS = ${cooldown};
var WEBHOOK = "${url}";
var LABEL = "${label}";
var SWITCH_KEY = "switch:${idx}";
var above = false;
var lastSentMs = 0;

function nowMs() { return Date.now(); }

function sendEvent(apower) {
  var payload = JSON.stringify({
    event: "power_threshold",
    label: LABEL,
    threshold_w: THRESHOLD_W,
    power_w: apower,
    device_id: Shelly.getDeviceInfo().id,
    at: nowMs()
  });
  Shelly.call(
    "HTTP.POST",
    { url: WEBHOOK, body: payload, content_type: "application/json" },
    function(_resp, err) {
      if (err) { print("dispatch: webhook error ", err); }
    }
  );
}

Shelly.addStatusHandler(function(ev) {
  if (!ev || ev.component !== SWITCH_KEY || !ev.delta) return;
  if (typeof ev.delta.apower !== "number") return;
  var p = ev.delta.apower;
  if (p > THRESHOLD_W && !above) {
    above = true;
    if (nowMs() - lastSentMs > COOLDOWN_MS) {
      lastSentMs = nowMs();
      sendEvent(p);
    }
  } else if (p < THRESHOLD_W * 0.8 && above) {
    above = false;
  }
});

print("dispatch: power-threshold watcher active on ", SWITCH_KEY, " threshold=", THRESHOLD_W, "W");
`.trim()
}

/**
 * Cycle-finish webhook.
 *
 * Detects the end of an appliance cycle: apower was above `runW` for
 * at least `minRunMs`, then drops below `idleW` and stays there for
 * `debounceMs`. Classic "laundry done" / "dishwasher done" pattern.
 */
export function cycleFinishWebhook(params: {
  switchIndex?: number
  runW: number
  idleW: number
  minRunMs: number
  debounceMs: number
  webhookUrl: string
  label?: string
}): string {
  const idx = params.switchIndex ?? 0
  const label = (params.label ?? '').replace(/"/g, '\\"')
  return `
// Auto-generated by HA Dispatch. Do not edit on device — re-deploy instead.
var RUN_W = ${params.runW};
var IDLE_W = ${params.idleW};
var MIN_RUN_MS = ${params.minRunMs};
var DEBOUNCE_MS = ${params.debounceMs};
var WEBHOOK = "${params.webhookUrl}";
var LABEL = "${label}";
var SWITCH_KEY = "switch:${idx}";

var state = "idle";
var runStart = 0;
var idleStart = 0;
var lastP = 0;

function nowMs() { return Date.now(); }

function send(kind, p) {
  var payload = JSON.stringify({
    event: kind,
    label: LABEL,
    power_w: p,
    device_id: Shelly.getDeviceInfo().id,
    at: nowMs()
  });
  Shelly.call("HTTP.POST", { url: WEBHOOK, body: payload, content_type: "application/json" },
    function(_r, err) { if (err) print("dispatch: webhook error ", err); });
}

Shelly.addStatusHandler(function(ev) {
  if (!ev || ev.component !== SWITCH_KEY || !ev.delta) return;
  if (typeof ev.delta.apower !== "number") return;
  lastP = ev.delta.apower;

  if (state === "idle" && lastP >= RUN_W) {
    state = "running";
    runStart = nowMs();
  } else if (state === "running" && lastP < IDLE_W) {
    state = "cooling";
    idleStart = nowMs();
  } else if (state === "cooling" && lastP >= RUN_W) {
    state = "running";
  }
});

Timer.set(DEBOUNCE_MS, true, function() {
  if (state === "cooling") {
    if (nowMs() - idleStart >= DEBOUNCE_MS && nowMs() - runStart >= MIN_RUN_MS) {
      send("cycle_finished", lastP);
      state = "idle";
    }
  }
});

print("dispatch: cycle-finish watcher active runW=", RUN_W, " idleW=", IDLE_W);
`.trim()
}

export const scriptTemplates = {
  power_threshold_webhook: powerThresholdWebhook,
  cycle_finish_webhook: cycleFinishWebhook,
} as const

export type ScriptTemplateId = keyof typeof scriptTemplates
